### ISSUE TITLE
Syntax error in @applitools/http-commons

### ISSUE THREAD

**Issue by justmoon** [applitools/eyes.cypress#5]
It looks like `@applitools/http-commons@1.0.23` requires a newer JavaScript engine than what the latest `cypress@3.1.0` provides.

As a result we get a SyntaxError:

```
 ✔  Verified Cypress! /root/.cache/Cypress/3.1.0/Cypress

Opening Cypress...
name_to_handle_at on /dev: Operation not permitted
The plugins file is missing or invalid.

Your pluginsFile is set to '/usr/src/app/cypress/plugins/index.js', but either the file is missing, it contains a syntax error, or threw an error when required. The pluginsFile must be a .js or .coffee file.

Please fix this, or set 'pluginsFile' to 'false' if a plugins file is not necessary for your project.

The following error was thrown:

/usr/src/app/node_modules/@applitools/http-commons/src/http-commons.js:203
  const fetchOptionsWithAgent = {agent: defaultAgent(u.protocol), ...fetchOptions}
                                                                  ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/app/node_modules/@applitools/visual-grid-client/src/sdk/fetchResource.js:3:22)
    at Object.<anonymous> (/usr/src/app/node_modules/@applitools/visual-grid-client/src/sdk/fetchResource.js:24:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
Exited with code 1
```

Fortunately, it is only a single instance in the code where such modern JS features are used, so this patch in `@applitools/http-commons/src/http-commons.js:203` makes it work fine:

``` diff
-   const fetchOptionsWithAgent = {agent: defaultAgent(u.protocol), ...fetchOptions}
+   const fetchOptionsWithAgent = Object.assign({agent: defaultAgent(u.protocol)}, fetchOptions)
```

**Comment by amitzur** [comment]
Thanks, and sorry for taking time to respond!
This is fixed now in v3.0.9
